add export script for exporting OSM-formatted buildings by precinct

diff --git a/script/export b/script/export
--- a/script/export
+++ b/script/export
@@ -1,8 +1,16 @@
 #!/bin/sh
 
-set -e
+# Export the buildings in a precinct to osm/$PRECINCT.osm
+#
+# Usage
+#   export -d pdx_osm -p 4302
+#   export -d pdx_osm
 
-usage() { echo "Usage: $0 [-d postgres database]" 1>&2; exit 1; }
+# pgsql2shp returns a a non-zero status for empty queries so this is commented
+# out for now.
+#set -e
+
+usage() { echo "Usage: $0 [-d postgres database] [-p precinct]" 1>&2; exit 1; }
 
 while getopts ":d:p:" opt; do
   case $opt in
@@ -36,11 +44,33 @@ if [[ -e osm/$precinct.osm ]]; then
   rm osm/$precinct.*
 fi
 
-pgsql2shp -p 15432 -f shp/$precinct.shp $dbname  "select buildings_final.* \
-  from precincts \
-  inner join buildings_final on st_intersects(precincts.geom, buildings_final.geom) \
-  where precinct = $precinct"
+# A specific precint wasn't given, so run through every precinct, splitting building
+# data into seperate files.
+if [ -z "${precinct}" ]; then
+  precincts=`psql -d $dbname -t -c "SELECT distinct(precinct::int) FROM precincts order by 1"`
+  for pid in $precincts; do
+    echo "\n${red}Exporting precinct $pid${nc}..."
 
-python lib/ogr2osm.py shp/$precinct.shp -t lib/translate-attributes.py -o osm/$precinct.osm
+    pgsql2shp -p 15432 -f shp/$pid.shp $dbname \
+      "select buildings_final.* \
+        from precincts \
+        inner join buildings_final on st_intersects(precincts.geom, buildings_final.geom) \
+        where precinct = $pid"
 
-rm shp/$precinct.*
+    python lib/ogr2osm.py -f shp/$pid.shp -t lib/translate-attributes.py -o osm/$pid.osm
+
+    rm shp/$pid.*
+  done
+# Export a single precinct supplied with the -p flag
+else
+  echo "\n${red}Exporting precinct $precinct ${nc}..."
+  pgsql2shp -p 15432 -f shp/$precinct.shp $dbname \
+    "select buildings_final.* \
+      from precincts \
+      inner join buildings_final on st_intersects(precincts.geom, buildings_final.geom) \
+      where precinct = $precinct"
+
+  python lib/ogr2osm.py -f shp/$precinct.shp -t lib/translate-attributes.py -o osm/$precinct.osm
+
+  rm shp/$precinct.*
+fi
